// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: core.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxInDescMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Script           []byte `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	Value            int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	ShortAbelAddress []byte `protobuf:"bytes,3,opt,name=shortAbelAddress,proto3" json:"shortAbelAddress,omitempty"`
	Height           int64  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Txid             []byte `protobuf:"bytes,5,opt,name=txid,proto3" json:"txid,omitempty"`
	Index            int32  `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *TxInDescMessage) Reset() {
	*x = TxInDescMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxInDescMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxInDescMessage) ProtoMessage() {}

func (x *TxInDescMessage) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxInDescMessage.ProtoReflect.Descriptor instead.
func (*TxInDescMessage) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *TxInDescMessage) GetScript() []byte {
	if x != nil {
		return x.Script
	}
	return nil
}

func (x *TxInDescMessage) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TxInDescMessage) GetShortAbelAddress() []byte {
	if x != nil {
		return x.ShortAbelAddress
	}
	return nil
}

func (x *TxInDescMessage) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TxInDescMessage) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *TxInDescMessage) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type TxOutDescMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbelAddress []byte `protobuf:"bytes,1,opt,name=abelAddress,proto3" json:"abelAddress,omitempty"`
	Value       int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TxOutDescMessage) Reset() {
	*x = TxOutDescMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxOutDescMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOutDescMessage) ProtoMessage() {}

func (x *TxOutDescMessage) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOutDescMessage.ProtoReflect.Descriptor instead.
func (*TxOutDescMessage) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *TxOutDescMessage) GetAbelAddress() []byte {
	if x != nil {
		return x.AbelAddress
	}
	return nil
}

func (x *TxOutDescMessage) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type BlockDescMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BinData []byte `protobuf:"bytes,1,opt,name=binData,proto3" json:"binData,omitempty"`
	Height  int64  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *BlockDescMessage) Reset() {
	*x = BlockDescMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockDescMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDescMessage) ProtoMessage() {}

func (x *BlockDescMessage) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDescMessage.ProtoReflect.Descriptor instead.
func (*BlockDescMessage) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *BlockDescMessage) GetBinData() []byte {
	if x != nil {
		return x.BinData
	}
	return nil
}

func (x *BlockDescMessage) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GenerateSafeCryptoSeedArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateSafeCryptoSeedArgs) Reset() {
	*x = GenerateSafeCryptoSeedArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateSafeCryptoSeedArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSafeCryptoSeedArgs) ProtoMessage() {}

func (x *GenerateSafeCryptoSeedArgs) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSafeCryptoSeedArgs.ProtoReflect.Descriptor instead.
func (*GenerateSafeCryptoSeedArgs) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

type GenerateSafeCryptoSeedResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CryptoSeed []byte `protobuf:"bytes,1,opt,name=cryptoSeed,proto3" json:"cryptoSeed,omitempty"`
}

func (x *GenerateSafeCryptoSeedResult) Reset() {
	*x = GenerateSafeCryptoSeedResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateSafeCryptoSeedResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSafeCryptoSeedResult) ProtoMessage() {}

func (x *GenerateSafeCryptoSeedResult) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSafeCryptoSeedResult.ProtoReflect.Descriptor instead.
func (*GenerateSafeCryptoSeedResult) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateSafeCryptoSeedResult) GetCryptoSeed() []byte {
	if x != nil {
		return x.CryptoSeed
	}
	return nil
}

type GenerateCryptoKeysAndAddressArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CryptoSeed []byte `protobuf:"bytes,1,opt,name=cryptoSeed,proto3" json:"cryptoSeed,omitempty"`
}

func (x *GenerateCryptoKeysAndAddressArgs) Reset() {
	*x = GenerateCryptoKeysAndAddressArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateCryptoKeysAndAddressArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCryptoKeysAndAddressArgs) ProtoMessage() {}

func (x *GenerateCryptoKeysAndAddressArgs) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCryptoKeysAndAddressArgs.ProtoReflect.Descriptor instead.
func (*GenerateCryptoKeysAndAddressArgs) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateCryptoKeysAndAddressArgs) GetCryptoSeed() []byte {
	if x != nil {
		return x.CryptoSeed
	}
	return nil
}

type GenerateCryptoKeysAndAddressResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpendSecretKey    []byte `protobuf:"bytes,1,opt,name=spendSecretKey,proto3" json:"spendSecretKey,omitempty"`
	SerialNoSecretKey []byte `protobuf:"bytes,2,opt,name=serialNoSecretKey,proto3" json:"serialNoSecretKey,omitempty"`
	ViewSecretKey     []byte `protobuf:"bytes,3,opt,name=viewSecretKey,proto3" json:"viewSecretKey,omitempty"`
	CryptoAddress     []byte `protobuf:"bytes,4,opt,name=cryptoAddress,proto3" json:"cryptoAddress,omitempty"`
}

func (x *GenerateCryptoKeysAndAddressResult) Reset() {
	*x = GenerateCryptoKeysAndAddressResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateCryptoKeysAndAddressResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCryptoKeysAndAddressResult) ProtoMessage() {}

func (x *GenerateCryptoKeysAndAddressResult) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCryptoKeysAndAddressResult.ProtoReflect.Descriptor instead.
func (*GenerateCryptoKeysAndAddressResult) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateCryptoKeysAndAddressResult) GetSpendSecretKey() []byte {
	if x != nil {
		return x.SpendSecretKey
	}
	return nil
}

func (x *GenerateCryptoKeysAndAddressResult) GetSerialNoSecretKey() []byte {
	if x != nil {
		return x.SerialNoSecretKey
	}
	return nil
}

func (x *GenerateCryptoKeysAndAddressResult) GetViewSecretKey() []byte {
	if x != nil {
		return x.ViewSecretKey
	}
	return nil
}

func (x *GenerateCryptoKeysAndAddressResult) GetCryptoAddress() []byte {
	if x != nil {
		return x.CryptoAddress
	}
	return nil
}

type GetAbelAddressFromCryptoAddressArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CryptoAddress []byte `protobuf:"bytes,1,opt,name=cryptoAddress,proto3" json:"cryptoAddress,omitempty"`
	ChainID       int32  `protobuf:"varint,2,opt,name=chainID,proto3" json:"chainID,omitempty"`
}

func (x *GetAbelAddressFromCryptoAddressArgs) Reset() {
	*x = GetAbelAddressFromCryptoAddressArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAbelAddressFromCryptoAddressArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbelAddressFromCryptoAddressArgs) ProtoMessage() {}

func (x *GetAbelAddressFromCryptoAddressArgs) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbelAddressFromCryptoAddressArgs.ProtoReflect.Descriptor instead.
func (*GetAbelAddressFromCryptoAddressArgs) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7}
}

func (x *GetAbelAddressFromCryptoAddressArgs) GetCryptoAddress() []byte {
	if x != nil {
		return x.CryptoAddress
	}
	return nil
}

func (x *GetAbelAddressFromCryptoAddressArgs) GetChainID() int32 {
	if x != nil {
		return x.ChainID
	}
	return 0
}

type GetAbelAddressFromCryptoAddressResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbelAddress []byte `protobuf:"bytes,1,opt,name=abelAddress,proto3" json:"abelAddress,omitempty"`
}

func (x *GetAbelAddressFromCryptoAddressResult) Reset() {
	*x = GetAbelAddressFromCryptoAddressResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAbelAddressFromCryptoAddressResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbelAddressFromCryptoAddressResult) ProtoMessage() {}

func (x *GetAbelAddressFromCryptoAddressResult) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbelAddressFromCryptoAddressResult.ProtoReflect.Descriptor instead.
func (*GetAbelAddressFromCryptoAddressResult) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8}
}

func (x *GetAbelAddressFromCryptoAddressResult) GetAbelAddress() []byte {
	if x != nil {
		return x.AbelAddress
	}
	return nil
}

type GetCryptoAddressFromAbelAddressArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbelAddress []byte `protobuf:"bytes,1,opt,name=abelAddress,proto3" json:"abelAddress,omitempty"`
}

func (x *GetCryptoAddressFromAbelAddressArgs) Reset() {
	*x = GetCryptoAddressFromAbelAddressArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCryptoAddressFromAbelAddressArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCryptoAddressFromAbelAddressArgs) ProtoMessage() {}

func (x *GetCryptoAddressFromAbelAddressArgs) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCryptoAddressFromAbelAddressArgs.ProtoReflect.Descriptor instead.
func (*GetCryptoAddressFromAbelAddressArgs) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{9}
}

func (x *GetCryptoAddressFromAbelAddressArgs) GetAbelAddress() []byte {
	if x != nil {
		return x.AbelAddress
	}
	return nil
}

type GetCryptoAddressFromAbelAddressResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CryptoAddress []byte `protobuf:"bytes,1,opt,name=cryptoAddress,proto3" json:"cryptoAddress,omitempty"`
}

func (x *GetCryptoAddressFromAbelAddressResult) Reset() {
	*x = GetCryptoAddressFromAbelAddressResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCryptoAddressFromAbelAddressResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCryptoAddressFromAbelAddressResult) ProtoMessage() {}

func (x *GetCryptoAddressFromAbelAddressResult) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCryptoAddressFromAbelAddressResult.ProtoReflect.Descriptor instead.
func (*GetCryptoAddressFromAbelAddressResult) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10}
}

func (x *GetCryptoAddressFromAbelAddressResult) GetCryptoAddress() []byte {
	if x != nil {
		return x.CryptoAddress
	}
	return nil
}

type GetShortAbelAddressFromAbelAddressArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbelAddress []byte `protobuf:"bytes,1,opt,name=abelAddress,proto3" json:"abelAddress,omitempty"`
}

func (x *GetShortAbelAddressFromAbelAddressArgs) Reset() {
	*x = GetShortAbelAddressFromAbelAddressArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShortAbelAddressFromAbelAddressArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortAbelAddressFromAbelAddressArgs) ProtoMessage() {}

func (x *GetShortAbelAddressFromAbelAddressArgs) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortAbelAddressFromAbelAddressArgs.ProtoReflect.Descriptor instead.
func (*GetShortAbelAddressFromAbelAddressArgs) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{11}
}

func (x *GetShortAbelAddressFromAbelAddressArgs) GetAbelAddress() []byte {
	if x != nil {
		return x.AbelAddress
	}
	return nil
}

type GetShortAbelAddressFromAbelAddressResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortAbelAddress []byte `protobuf:"bytes,1,opt,name=shortAbelAddress,proto3" json:"shortAbelAddress,omitempty"`
}

func (x *GetShortAbelAddressFromAbelAddressResult) Reset() {
	*x = GetShortAbelAddressFromAbelAddressResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShortAbelAddressFromAbelAddressResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortAbelAddressFromAbelAddressResult) ProtoMessage() {}

func (x *GetShortAbelAddressFromAbelAddressResult) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortAbelAddressFromAbelAddressResult.ProtoReflect.Descriptor instead.
func (*GetShortAbelAddressFromAbelAddressResult) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{12}
}

func (x *GetShortAbelAddressFromAbelAddressResult) GetShortAbelAddress() []byte {
	if x != nil {
		return x.ShortAbelAddress
	}
	return nil
}

type DecodeFingerprintFromTxVoutScriptArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxVoutScript []byte `protobuf:"bytes,1,opt,name=txVoutScript,proto3" json:"txVoutScript,omitempty"`
}

func (x *DecodeFingerprintFromTxVoutScriptArgs) Reset() {
	*x = DecodeFingerprintFromTxVoutScriptArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodeFingerprintFromTxVoutScriptArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeFingerprintFromTxVoutScriptArgs) ProtoMessage() {}

func (x *DecodeFingerprintFromTxVoutScriptArgs) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeFingerprintFromTxVoutScriptArgs.ProtoReflect.Descriptor instead.
func (*DecodeFingerprintFromTxVoutScriptArgs) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{13}
}

func (x *DecodeFingerprintFromTxVoutScriptArgs) GetTxVoutScript() []byte {
	if x != nil {
		return x.TxVoutScript
	}
	return nil
}

type DecodeFingerprintFromTxVoutScriptResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fingerprint []byte `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
}

func (x *DecodeFingerprintFromTxVoutScriptResult) Reset() {
	*x = DecodeFingerprintFromTxVoutScriptResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodeFingerprintFromTxVoutScriptResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeFingerprintFromTxVoutScriptResult) ProtoMessage() {}

func (x *DecodeFingerprintFromTxVoutScriptResult) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeFingerprintFromTxVoutScriptResult.ProtoReflect.Descriptor instead.
func (*DecodeFingerprintFromTxVoutScriptResult) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{14}
}

func (x *DecodeFingerprintFromTxVoutScriptResult) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

type DecodeCoinValueFromTxVoutScriptArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxVoutScript  []byte `protobuf:"bytes,1,opt,name=txVoutScript,proto3" json:"txVoutScript,omitempty"`
	ViewSecretKey []byte `protobuf:"bytes,2,opt,name=viewSecretKey,proto3" json:"viewSecretKey,omitempty"`
}

func (x *DecodeCoinValueFromTxVoutScriptArgs) Reset() {
	*x = DecodeCoinValueFromTxVoutScriptArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodeCoinValueFromTxVoutScriptArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeCoinValueFromTxVoutScriptArgs) ProtoMessage() {}

func (x *DecodeCoinValueFromTxVoutScriptArgs) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeCoinValueFromTxVoutScriptArgs.ProtoReflect.Descriptor instead.
func (*DecodeCoinValueFromTxVoutScriptArgs) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{15}
}

func (x *DecodeCoinValueFromTxVoutScriptArgs) GetTxVoutScript() []byte {
	if x != nil {
		return x.TxVoutScript
	}
	return nil
}

func (x *DecodeCoinValueFromTxVoutScriptArgs) GetViewSecretKey() []byte {
	if x != nil {
		return x.ViewSecretKey
	}
	return nil
}

type DecodeCoinValueFromTxVoutScriptResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CoinValue int64 `protobuf:"varint,1,opt,name=coinValue,proto3" json:"coinValue,omitempty"`
}

func (x *DecodeCoinValueFromTxVoutScriptResult) Reset() {
	*x = DecodeCoinValueFromTxVoutScriptResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodeCoinValueFromTxVoutScriptResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeCoinValueFromTxVoutScriptResult) ProtoMessage() {}

func (x *DecodeCoinValueFromTxVoutScriptResult) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeCoinValueFromTxVoutScriptResult.ProtoReflect.Descriptor instead.
func (*DecodeCoinValueFromTxVoutScriptResult) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{16}
}

func (x *DecodeCoinValueFromTxVoutScriptResult) GetCoinValue() int64 {
	if x != nil {
		return x.CoinValue
	}
	return 0
}

type GenerateUnsignedRawTxDataArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxInDescs        []*TxInDescMessage  `protobuf:"bytes,1,rep,name=txInDescs,proto3" json:"txInDescs,omitempty"`
	TxOutDescs       []*TxOutDescMessage `protobuf:"bytes,2,rep,name=txOutDescs,proto3" json:"txOutDescs,omitempty"`
	TxRingBlockDescs []*BlockDescMessage `protobuf:"bytes,3,rep,name=txRingBlockDescs,proto3" json:"txRingBlockDescs,omitempty"`
	TxFee            int64               `protobuf:"varint,4,opt,name=txFee,proto3" json:"txFee,omitempty"`
}

func (x *GenerateUnsignedRawTxDataArgs) Reset() {
	*x = GenerateUnsignedRawTxDataArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateUnsignedRawTxDataArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUnsignedRawTxDataArgs) ProtoMessage() {}

func (x *GenerateUnsignedRawTxDataArgs) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUnsignedRawTxDataArgs.ProtoReflect.Descriptor instead.
func (*GenerateUnsignedRawTxDataArgs) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{17}
}

func (x *GenerateUnsignedRawTxDataArgs) GetTxInDescs() []*TxInDescMessage {
	if x != nil {
		return x.TxInDescs
	}
	return nil
}

func (x *GenerateUnsignedRawTxDataArgs) GetTxOutDescs() []*TxOutDescMessage {
	if x != nil {
		return x.TxOutDescs
	}
	return nil
}

func (x *GenerateUnsignedRawTxDataArgs) GetTxRingBlockDescs() []*BlockDescMessage {
	if x != nil {
		return x.TxRingBlockDescs
	}
	return nil
}

func (x *GenerateUnsignedRawTxDataArgs) GetTxFee() int64 {
	if x != nil {
		return x.TxFee
	}
	return 0
}

type GenerateUnsignedRawTxDataResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	SignerShortAddresses [][]byte `protobuf:"bytes,2,rep,name=signerShortAddresses,proto3" json:"signerShortAddresses,omitempty"`
}

func (x *GenerateUnsignedRawTxDataResult) Reset() {
	*x = GenerateUnsignedRawTxDataResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateUnsignedRawTxDataResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUnsignedRawTxDataResult) ProtoMessage() {}

func (x *GenerateUnsignedRawTxDataResult) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUnsignedRawTxDataResult.ProtoReflect.Descriptor instead.
func (*GenerateUnsignedRawTxDataResult) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{18}
}

func (x *GenerateUnsignedRawTxDataResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GenerateUnsignedRawTxDataResult) GetSignerShortAddresses() [][]byte {
	if x != nil {
		return x.SignerShortAddresses
	}
	return nil
}

type GenerateSignedRawTxDataArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnsignedRawTxData    []byte   `protobuf:"bytes,1,opt,name=unsignedRawTxData,proto3" json:"unsignedRawTxData,omitempty"`
	SignerShortAddresses [][]byte `protobuf:"bytes,2,rep,name=signerShortAddresses,proto3" json:"signerShortAddresses,omitempty"`
	SignerCryptoSeeds    [][]byte `protobuf:"bytes,3,rep,name=signerCryptoSeeds,proto3" json:"signerCryptoSeeds,omitempty"`
}

func (x *GenerateSignedRawTxDataArgs) Reset() {
	*x = GenerateSignedRawTxDataArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateSignedRawTxDataArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSignedRawTxDataArgs) ProtoMessage() {}

func (x *GenerateSignedRawTxDataArgs) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSignedRawTxDataArgs.ProtoReflect.Descriptor instead.
func (*GenerateSignedRawTxDataArgs) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{19}
}

func (x *GenerateSignedRawTxDataArgs) GetUnsignedRawTxData() []byte {
	if x != nil {
		return x.UnsignedRawTxData
	}
	return nil
}

func (x *GenerateSignedRawTxDataArgs) GetSignerShortAddresses() [][]byte {
	if x != nil {
		return x.SignerShortAddresses
	}
	return nil
}

func (x *GenerateSignedRawTxDataArgs) GetSignerCryptoSeeds() [][]byte {
	if x != nil {
		return x.SignerCryptoSeeds
	}
	return nil
}

type GenerateSignedRawTxDataResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Txid []byte `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
}

func (x *GenerateSignedRawTxDataResult) Reset() {
	*x = GenerateSignedRawTxDataResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateSignedRawTxDataResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSignedRawTxDataResult) ProtoMessage() {}

func (x *GenerateSignedRawTxDataResult) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSignedRawTxDataResult.ProtoReflect.Descriptor instead.
func (*GenerateSignedRawTxDataResult) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{20}
}

func (x *GenerateSignedRawTxDataResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GenerateSignedRawTxDataResult) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

type GenerateCoinSerialNumberArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txid              []byte              `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Index             int32               `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	SerialNoSecretKey []byte              `protobuf:"bytes,3,opt,name=serialNoSecretKey,proto3" json:"serialNoSecretKey,omitempty"`
	RingBlockDescs    []*BlockDescMessage `protobuf:"bytes,4,rep,name=ringBlockDescs,proto3" json:"ringBlockDescs,omitempty"`
}

func (x *GenerateCoinSerialNumberArgs) Reset() {
	*x = GenerateCoinSerialNumberArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateCoinSerialNumberArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCoinSerialNumberArgs) ProtoMessage() {}

func (x *GenerateCoinSerialNumberArgs) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCoinSerialNumberArgs.ProtoReflect.Descriptor instead.
func (*GenerateCoinSerialNumberArgs) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{21}
}

func (x *GenerateCoinSerialNumberArgs) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *GenerateCoinSerialNumberArgs) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GenerateCoinSerialNumberArgs) GetSerialNoSecretKey() []byte {
	if x != nil {
		return x.SerialNoSecretKey
	}
	return nil
}

func (x *GenerateCoinSerialNumberArgs) GetRingBlockDescs() []*BlockDescMessage {
	if x != nil {
		return x.RingBlockDescs
	}
	return nil
}

type GenerateCoinSerialNumberResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SerialNumber []byte `protobuf:"bytes,1,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
}

func (x *GenerateCoinSerialNumberResult) Reset() {
	*x = GenerateCoinSerialNumberResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateCoinSerialNumberResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCoinSerialNumberResult) ProtoMessage() {}

func (x *GenerateCoinSerialNumberResult) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCoinSerialNumberResult.ProtoReflect.Descriptor instead.
func (*GenerateCoinSerialNumberResult) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{22}
}

func (x *GenerateCoinSerialNumberResult) GetSerialNumber() []byte {
	if x != nil {
		return x.SerialNumber
	}
	return nil
}

var File_core_proto protoreflect.FileDescriptor

var file_core_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x6f,
	0x72, 0x65, 0x22, 0xad, 0x01, 0x0a, 0x0f, 0x54, 0x78, 0x49, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x41, 0x62, 0x65,
	0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x41, 0x62, 0x65, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x22, 0x4a, 0x0a, 0x10, 0x54, 0x78, 0x4f, 0x75, 0x74, 0x44, 0x65, 0x73, 0x63, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x62, 0x65, 0x6c, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x62, 0x65,
	0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x44,
	0x0a, 0x10, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x65, 0x73, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x62, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x53, 0x61, 0x66, 0x65, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x53, 0x65, 0x65, 0x64, 0x41, 0x72,
	0x67, 0x73, 0x22, 0x3e, 0x0a, 0x1c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x61,
	0x66, 0x65, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x53, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x53, 0x65, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x53, 0x65,
	0x65, 0x64, 0x22, 0x42, 0x0a, 0x20, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x72,
	0x79, 0x70, 0x74, 0x6f, 0x4b, 0x65, 0x79, 0x73, 0x41, 0x6e, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x41, 0x72, 0x67, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x53, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x53, 0x65, 0x65, 0x64, 0x22, 0xc6, 0x01, 0x0a, 0x22, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x4b, 0x65, 0x79, 0x73, 0x41, 0x6e, 0x64,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a,
	0x0e, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e,
	0x6f, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x11, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x6f, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x76, 0x69, 0x65, 0x77, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x76, 0x69, 0x65, 0x77,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0d, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x65, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x41, 0x62, 0x65, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x41, 0x72, 0x67, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x22, 0x49, 0x0a, 0x25, 0x47, 0x65, 0x74, 0x41, 0x62, 0x65,
	0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x61, 0x62, 0x65, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x62, 0x65, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x22, 0x47, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x62, 0x65, 0x6c, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x41, 0x72, 0x67, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x62, 0x65, 0x6c,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61,
	0x62, 0x65, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x4d, 0x0a, 0x25, 0x47, 0x65,
	0x74, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x46, 0x72,
	0x6f, 0x6d, 0x41, 0x62, 0x65, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x4a, 0x0a, 0x26, 0x47, 0x65, 0x74,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x41, 0x62, 0x65, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x46, 0x72, 0x6f, 0x6d, 0x41, 0x62, 0x65, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x41,
	0x72, 0x67, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x62, 0x65, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x62, 0x65, 0x6c, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x56, 0x0a, 0x28, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x41, 0x62, 0x65, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x46, 0x72, 0x6f, 0x6d,
	0x41, 0x62, 0x65, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x41, 0x62, 0x65, 0x6c, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x41, 0x62, 0x65, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x4b, 0x0a,
	0x25, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69,
	0x6e, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x78, 0x56, 0x6f, 0x75, 0x74, 0x53, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x41, 0x72, 0x67, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x78, 0x56, 0x6f, 0x75, 0x74,
	0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x74, 0x78,
	0x56, 0x6f, 0x75, 0x74, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x22, 0x4b, 0x0a, 0x27, 0x44, 0x65,
	0x63, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x46,
	0x72, 0x6f, 0x6d, 0x54, 0x78, 0x56, 0x6f, 0x75, 0x74, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70,
	0x72, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x22, 0x6f, 0x0a, 0x23, 0x44, 0x65, 0x63, 0x6f, 0x64,
	0x65, 0x43, 0x6f, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x78,
	0x56, 0x6f, 0x75, 0x74, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x41, 0x72, 0x67, 0x73, 0x12, 0x22,
	0x0a, 0x0c, 0x74, 0x78, 0x56, 0x6f, 0x75, 0x74, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x74, 0x78, 0x56, 0x6f, 0x75, 0x74, 0x53, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x76, 0x69, 0x65, 0x77, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x76, 0x69, 0x65, 0x77, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x22, 0x45, 0x0a, 0x25, 0x44, 0x65, 0x63, 0x6f,
	0x64, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x54,
	0x78, 0x56, 0x6f, 0x75, 0x74, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0xe6, 0x01, 0x0a, 0x1d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x64, 0x52, 0x61, 0x77, 0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x41, 0x72, 0x67,
	0x73, 0x12, 0x33, 0x0a, 0x09, 0x74, 0x78, 0x49, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x54, 0x78, 0x49, 0x6e,
	0x44, 0x65, 0x73, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x09, 0x74, 0x78, 0x49,
	0x6e, 0x44, 0x65, 0x73, 0x63, 0x73, 0x12, 0x36, 0x0a, 0x0a, 0x74, 0x78, 0x4f, 0x75, 0x74, 0x44,
	0x65, 0x73, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x54, 0x78, 0x4f, 0x75, 0x74, 0x44, 0x65, 0x73, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x0a, 0x74, 0x78, 0x4f, 0x75, 0x74, 0x44, 0x65, 0x73, 0x63, 0x73, 0x12, 0x42,
	0x0a, 0x10, 0x74, 0x78, 0x52, 0x69, 0x6e, 0x67, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x65, 0x73,
	0x63, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x65, 0x73, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x10, 0x74, 0x78, 0x52, 0x69, 0x6e, 0x67, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x65, 0x73,
	0x63, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x78, 0x46, 0x65, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x74, 0x78, 0x46, 0x65, 0x65, 0x22, 0x69, 0x0a, 0x1f, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x52, 0x61, 0x77, 0x54,
	0x78, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x32, 0x0a, 0x14, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x14, 0x73,
	0x69, 0x67, 0x6e, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x22, 0xad, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x52, 0x61, 0x77, 0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x41,
	0x72, 0x67, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x75, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x52,
	0x61, 0x77, 0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11,
	0x75, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x52, 0x61, 0x77, 0x54, 0x78, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x32, 0x0a, 0x14, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x14, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x43,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x53, 0x65, 0x65, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x11, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x53, 0x65,
	0x65, 0x64, 0x73, 0x22, 0x47, 0x0a, 0x1d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x52, 0x61, 0x77, 0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x22, 0xb6, 0x01, 0x0a,
	0x1c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x53, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x78, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x78, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x4e, 0x6f, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x11, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x6f, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x3e, 0x0a, 0x0e, 0x72, 0x69, 0x6e, 0x67, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x44, 0x65, 0x73, 0x63, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x65, 0x73, 0x63, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0e, 0x72, 0x69, 0x6e, 0x67, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x44, 0x65, 0x73, 0x63, 0x73, 0x22, 0x44, 0x0a, 0x1e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x73,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x30, 0x0a, 0x16, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x61, 0x62, 0x65, 0x6c, 0x69, 0x61, 0x6e, 0x2e, 0x73, 0x64, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x16, 0x61, 0x62, 0x65, 0x6c, 0x69, 0x61, 0x6e, 0x2e, 0x69,
	0x6e, 0x66, 0x6f, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData = file_core_proto_rawDesc
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_proto_rawDescData)
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_core_proto_goTypes = []interface{}{
	(*TxInDescMessage)(nil),                          // 0: core.TxInDescMessage
	(*TxOutDescMessage)(nil),                         // 1: core.TxOutDescMessage
	(*BlockDescMessage)(nil),                         // 2: core.BlockDescMessage
	(*GenerateSafeCryptoSeedArgs)(nil),               // 3: core.GenerateSafeCryptoSeedArgs
	(*GenerateSafeCryptoSeedResult)(nil),             // 4: core.GenerateSafeCryptoSeedResult
	(*GenerateCryptoKeysAndAddressArgs)(nil),         // 5: core.GenerateCryptoKeysAndAddressArgs
	(*GenerateCryptoKeysAndAddressResult)(nil),       // 6: core.GenerateCryptoKeysAndAddressResult
	(*GetAbelAddressFromCryptoAddressArgs)(nil),      // 7: core.GetAbelAddressFromCryptoAddressArgs
	(*GetAbelAddressFromCryptoAddressResult)(nil),    // 8: core.GetAbelAddressFromCryptoAddressResult
	(*GetCryptoAddressFromAbelAddressArgs)(nil),      // 9: core.GetCryptoAddressFromAbelAddressArgs
	(*GetCryptoAddressFromAbelAddressResult)(nil),    // 10: core.GetCryptoAddressFromAbelAddressResult
	(*GetShortAbelAddressFromAbelAddressArgs)(nil),   // 11: core.GetShortAbelAddressFromAbelAddressArgs
	(*GetShortAbelAddressFromAbelAddressResult)(nil), // 12: core.GetShortAbelAddressFromAbelAddressResult
	(*DecodeFingerprintFromTxVoutScriptArgs)(nil),    // 13: core.DecodeFingerprintFromTxVoutScriptArgs
	(*DecodeFingerprintFromTxVoutScriptResult)(nil),  // 14: core.DecodeFingerprintFromTxVoutScriptResult
	(*DecodeCoinValueFromTxVoutScriptArgs)(nil),      // 15: core.DecodeCoinValueFromTxVoutScriptArgs
	(*DecodeCoinValueFromTxVoutScriptResult)(nil),    // 16: core.DecodeCoinValueFromTxVoutScriptResult
	(*GenerateUnsignedRawTxDataArgs)(nil),            // 17: core.GenerateUnsignedRawTxDataArgs
	(*GenerateUnsignedRawTxDataResult)(nil),          // 18: core.GenerateUnsignedRawTxDataResult
	(*GenerateSignedRawTxDataArgs)(nil),              // 19: core.GenerateSignedRawTxDataArgs
	(*GenerateSignedRawTxDataResult)(nil),            // 20: core.GenerateSignedRawTxDataResult
	(*GenerateCoinSerialNumberArgs)(nil),             // 21: core.GenerateCoinSerialNumberArgs
	(*GenerateCoinSerialNumberResult)(nil),           // 22: core.GenerateCoinSerialNumberResult
}
var file_core_proto_depIdxs = []int32{
	0, // 0: core.GenerateUnsignedRawTxDataArgs.txInDescs:type_name -> core.TxInDescMessage
	1, // 1: core.GenerateUnsignedRawTxDataArgs.txOutDescs:type_name -> core.TxOutDescMessage
	2, // 2: core.GenerateUnsignedRawTxDataArgs.txRingBlockDescs:type_name -> core.BlockDescMessage
	2, // 3: core.GenerateCoinSerialNumberArgs.ringBlockDescs:type_name -> core.BlockDescMessage
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxInDescMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxOutDescMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockDescMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateSafeCryptoSeedArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateSafeCryptoSeedResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateCryptoKeysAndAddressArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateCryptoKeysAndAddressResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAbelAddressFromCryptoAddressArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAbelAddressFromCryptoAddressResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCryptoAddressFromAbelAddressArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCryptoAddressFromAbelAddressResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShortAbelAddressFromAbelAddressArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShortAbelAddressFromAbelAddressResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodeFingerprintFromTxVoutScriptArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodeFingerprintFromTxVoutScriptResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodeCoinValueFromTxVoutScriptArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodeCoinValueFromTxVoutScriptResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateUnsignedRawTxDataArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateUnsignedRawTxDataResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateSignedRawTxDataArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateSignedRawTxDataResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateCoinSerialNumberArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateCoinSerialNumberResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_rawDesc = nil
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
